version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis-broker
    ports:
      - "6379:6379"
    restart: always
    networks:
      - default
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - default
    command: >
      bash -c "
      /etc/confluent/docker/run &
      sleep 10 &&
      kafka-topics --create --if-not-exists --topic data-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&

      kafka-topics --create --if-not-exists --topic js-channel-oferta --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      
      kafka-topics --create --if-not-exists --topic pr-channel-datatype-usuarios --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic pr-channel-datatype-productos --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic pr-channel-datatype-transacciones --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic pr-construction-eventmessage-nuevo-evento --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic pr-construction-eventmessage-evento-procesado --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&

      kafka-topics --create --if-not-exists --topic dc-invalid-message --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic pv-course-assignments --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic gj-failed-messages --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&      
      kafka-topics --create --if-not-exists --topic pv-message-notifications --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&      
      
      kafka-topics --create --if-not-exists --topic course-assignments --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      
      kafka-topics --create --if-not-exists --topic gj-failed-messages --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&   
      
      wait
      "

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
